apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: go-epseevxp
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: go-epseevxp 
  name: go-epseevxp
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: go-epseevxp
    weight: 100 
